name: Docker Build and Push

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: giovannidegiorgio/sonsofthedocker:latest
      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:  giovannidegiorgio/sonsofthedocker:${{ github.ref_name }}
