name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag is $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Determine new version
        id: semver
        uses: anothrNick/github-tag-action@1.20.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: giovannidegiorgio/sons-of-the-docker:latest
      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:  giovannidegiorgio/sons-of-the-docker:latest
